<?php

/**
 * @file
 * Provides Bootstrap's tab styles to the Quicktabs module. Adapted from the
 * re_quicktabs_foundation module.
 *
 * @author Colin Calnan
 * @author Christopher Torgalson
 * @see https://bitbucket.org/reyebrow/re_quicktabs_foundation
 */


/**
 * Implements hook_quicktabs_renderers().
 */
function bh_bootstrapquicktabs_quicktabs_renderers() {
  $info = array();
  $path = drupal_get_path('module', 'bh_bootstrapquicktabs');
  $info['bh_bootstrapquicktabs_tabs'] = array(
    'path' => $path,
    'handler' => array(
      'file' => 'QuickBhBootstrapTabs.inc',
      'class' => 'QuickBhBootstrapTabs',
    ),
  );
  return $info;
} // bh_bootstrapquicktabs_quicktabs_renderers()


/**
 * Implements hook_theme().
 */
function bh_bootstrapquicktabs_theme() {
  return array(
    'bh_bootstrapquicktabs_tabs' => array(
      'render element' => 'element',
    ),
    'bh_bootstrapquicktabs_tabs_tabset' => array(
      'render element' => 'tabset',
    ),
  );
} // bh_bootstrapquicktabs_theme()


/**
 * Theme function to output tablinks for Foundation style tabs.
 *
 * @ingroup themeable
 */
function theme_bh_bootstrapquicktabs_tabs_tabset($variables) {
  // Empty set of tabs:
  $tabs = '';
  foreach (element_children($variables['tabset']['tablinks']) as $key) {
    if (is_array($variables['tabset']['tablinks'])) {
      $tabs .= '<li' . (($key == $variables['tabset']['#options']['active']) ? ' class="active"' : '') . '>';
      $tabs .= drupal_render($variables['tabset']['tablinks'][$key]);
      $tabs .= '</li>';
    }
  }
  return '<ul class="nav nav-tabs">' . $tabs . '</ul>';
} // theme_bh_bootstrapquicktabs_tabs_tabset()


/**
 * Theme function to output content for Bootstrap style tabs.
 *
 * @ingroup themeable
 */
function theme_bh_bootstrapquicktabs_tabs($variables) {
  // Prepare various information we need:
  //
  // Set aside the 'element' from the array for convenience:
  $element = $variables['element'];
  // Figure out the output pattern--we need to reverse the order of tabs and
  // panes if this is the 'below' kind of tabs:
  $output_pattern = $element['tabs']['#options']['type'] != 'below' ? '<div%1$s>%2$s%3$s</div>' : '<div%1$s>%3$s%2$s</div>';

  // Prepare the tabs:
  $tabs = drupal_render($element['tabs']);

  // Prepare the panes:
  $panes = '<div class="tab-content">';
  foreach ($element['panes'] as $pane) {
    $panes .= drupal_render($pane);
  }
  $panes .= '</div>';

  // Build and return the output:
  return sprintf($output_pattern, drupal_attributes($element['#options']['attributes']), $tabs, $panes);
} // theme_bh_bootstrapquicktabs_tabs()
